// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

var place1 = /* record */[
  /* id */"tel-aviv-port",
  /* name */"Tel aviv Port",
  /* description */"The port of tel aviv",
  /* image : record */[
    /* url */"bla",
    /* attribution */"Hello",
    /* attributionUrl */undefined
  ],
  /* address */"Tel aviv port 1",
  /* phone */undefined,
  /* email */undefined,
  /* coordinates : tuple */[
    1.2,
    2.3
  ]
];

var place2 = /* record */[
  /* id */"the-streets-id",
  /* name */"The Streets Cafe",
  /* description */"The best place to learn and work",
  /* image : record */[
    /* url */"bla",
    /* attribution */"Hello",
    /* attributionUrl */undefined
  ],
  /* address */"King George",
  /* phone */"1-800-",
  /* email */"thestreetsCafe@gmail.com",
  /* coordinates : tuple */[
    1.2,
    2.3
  ]
];

var place3 = /* record */[
  /* id */"sarona-market-id",
  /* name */"Sarona Market",
  /* description */"A market surrounnded with some of the most\n    prominnent institutions and hight tech companies in israel",
  /* image : record */[
    /* url */"bla",
    /* attribution */"Hello",
    /* attributionUrl */undefined
  ],
  /* address */"sarona market 1",
  /* phone */undefined,
  /* email */undefined,
  /* coordinates : tuple */[
    1.2,
    2.3
  ]
];

var places_001 = /* :: */[
  place2,
  /* :: */[
    place3,
    /* [] */0
  ]
];

var places = /* :: */[
  place1,
  places_001
];

var placesArray = $$Array.of_list(places);

var placeNames = List.map((function (place) {
        return place[/* name */1];
      }), places);

function searchPlaces(value) {
  if (value === "") {
    return places;
  } else {
    var lowercaseNameValue = $$String.lowercase(value);
    return List.filter((function (place) {
                    return $$String.lowercase(place[/* name */1]).includes(lowercaseNameValue);
                  }))(places);
  }
}

exports.place1 = place1;
exports.place2 = place2;
exports.place3 = place3;
exports.places = places;
exports.placesArray = placesArray;
exports.placeNames = placeNames;
exports.searchPlaces = searchPlaces;
/* placesArray Not a pure module */
