// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ListComponent$ReactHooksTemplate = require("./ListComponent.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(ListComponent$ReactHooksTemplate.make, { }), "place-list");

/*  Not a pure module */
