// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Data$ReactHooksTemplate = require("./Data.bs.js");
var Place$ReactHooksTemplate = require("./Place.bs.js");

function ListComponent(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setState = match[1];
  var onInputChange = function ($$event) {
    return Curry._1(setState, $$event.target.value);
  };
  return React.createElement("div", undefined, React.createElement("input", {
                  onInput: onInputChange
                }), Belt_Array.map(Belt_List.toArray(Data$ReactHooksTemplate.searchPlaces(match[0])), (function (place) {
                    return React.createElement(Place$ReactHooksTemplate.make, {
                                place: place,
                                key: place[/* id */0]
                              });
                  })));
}

var make = ListComponent;

exports.make = make;
/* react Not a pure module */
