// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Place(Props) {
  var place = Props.place;
  var match = place[/* phone */5];
  var match$1 = place[/* image */3][/* attributionUrl */2];
  return React.createElement("div", undefined, React.createElement("h1", undefined, place[/* name */1]), React.createElement("h3", undefined, place[/* description */2]), React.createElement("h4", undefined, place[/* address */4]), match !== undefined ? React.createElement("h3", undefined, match) : null, React.createElement("img", {
                  src: place[/* image */3][/* url */0]
                }), React.createElement("p", {
                  href: match$1 !== undefined ? match$1 : ""
                }, place[/* image */3][/* attribution */1]));
}

var make = Place;

exports.make = make;
/* react Not a pure module */
